### ISSUE TITLE
EEPROM contents

### ISSUE THREAD

**Issue by jmatyas** [quartiq/kasli-i2c#1]
What content is intended to be placed in the following EEPROM fields:
  * vendor_data
  * project_data
  * user_data
  * board_data?

According to comments in the code, the  _vendor_data_  field might be used for storing board serial number or data. However, I see no suggestion what to place in the other three fields. Were they reserved with something specific in mind and if so, has any specific format for it been developed? Or  perhaps those fields were created just for 'future development'?

**Comment by jordens** [comment]
* `vendor_data` is up to each vendor (or multiple vendors in the production, testing, configuration chain). Use it for batch number or vendor-specific serial number (but that would be a waste of space since the boards are already uniquely identified by `eui48`).
* `project_data` is reserved and currently unused space for the Sinara-HW project.
* `user_data` is up to each user to define. Won't be touched or used by vendor, ARTIQ, or other shared tooling.
* `board_data` is up to the Sinara-HW project to define for each board. E.g. for Urukul we use it to store calibration seeds for deterministic synchronization. Could be gains/offsets for Sampler.

**Comment by jordens** [comment]
But @jmatyas, what are the requirements of the vendors?

**Comment by jmatyas** [comment]
Great, thanks!

> But @jmatyas, what are the requirements of the vendors?

The vendors don't have any specific requirements so far. We just want to agree on a common standard of the EEPROM contents to allow the vendors to flash EEPROMs before sending the modules away.

**Comment by jordens** [comment]
Since there hasn't been any comment in the years since this format has been proposed and used, it seems safe to assume people are happy with it or don't care.

One general requirement is that the data in the EEPROM is absolutely minimal and that each bit has a reason to be there. In many cases it's much better and easier to store data somewhere else and then use the EUI-48 to reference that data (like calibration, configuration, and testing data). Many boards also have plenty of other storage space on them. The µC flashes on Stabilizer, Humpback, the FPGA config flashes on Humpback, Banker, Fastino, and even the CPLD config memory can be used to store data.

**Comment by sbourdeauducq** [comment]
> One general requirement is that the data in the EEPROM is absolutely minimal and that each bit has a reason to be there. In many cases it's much better and easier to store data somewhere else and then use the EUI-48 to reference that data (like calibration, configuration, and testing data).

Earlier you wanted the Urukul calibration data to be stored in that EEPROM, and this is what I implemented based on your recommendation. Has your position changed?

**Comment by jordens** [comment]
Using the CPLD would not be possible through the EEM interface. Storing in Kasli and referencing through eui-48 can certainly be argued for but it looks like it would require quite some additional tooling. I don't think the device db would be the right place as long as its role is unclear. It seems to me that pretty much everyone misunderstands the device db: most people think it is the autoritative source configuration while in fact it has little freedom beyond mirroring what the gateware and firmware already define and know. Maybe we should rethink that device db and consider refactor/splitting it into a fixed description of the system/gateware/firmware and the part that is actually configurable.
